In [4]:
import numpy as np

In [2]:
sales = [3343,4233,5465,4849]
profit = [234,453,456,243]
profitratio = []
for i in range(0,len(sales)):
    profitratio.append(profit[i]/sales[i])
profitratio

[0.06999700867484296,
 0.10701630049610206,
 0.08344007319304667,
 0.05011342544854609]

In [5]:
sales_array = np.array(sales)

In [6]:
profit_array = np.array(profit)

In [8]:
profit_array/sales_array

array([0.06999701, 0.1070163 , 0.08344007, 0.05011343])

In [11]:
import time 
size = 1000000
l1 = range(size)
l2 = range(size)
A1 = np.arange(size)
A2 = np.arange(size)
start = time.time()
result =[(x,y) for x,y in zip(l1,l2)]
print('time take by list')
print((time.time()-start)*1000)

start = time.time()
result = A1+A2
print('time take by array')
print((time.time()-start)*1000)

time take by list
353.3477783203125
time take by array
82.78012275695801


In [14]:
sales_us = [1323,3434,3323,4543]
sales_eu = [2432,3454,6475,2342]
sales_jp = [2434,5345,9877,5453]
sales_matrix = np.array([sales_us,sales_eu,sales_jp])

In [15]:
sales_matrix

array([[1323, 3434, 3323, 4543],
       [2432, 3454, 6475, 2342],
       [2434, 5345, 9877, 5453]])

In [16]:
profit_us = [133,334,323,453]
profit_eu = [432,354,675,232]
profit_jp = [434,535,977,553]
profit_matrix = np.array([profit_us,profit_eu,profit_jp])

In [17]:
profit_matrix

array([[133, 334, 323, 453],
       [432, 354, 675, 232],
       [434, 535, 977, 553]])

In [18]:
profit_matrix/sales_matrix

array([[0.1005291 , 0.09726267, 0.09720132, 0.09971385],
       [0.17763158, 0.10248987, 0.1042471 , 0.09906063],
       [0.17830731, 0.10009355, 0.09891668, 0.10141207]])

In [20]:
sales_matrix[2,3]

5453

In [22]:
sales_matrix[2:4, 0:3]

array([[2434, 5345, 9877]])

In [23]:
rdict = {'US':0, 'EU':1, 'JP':2}
qdict = {'Q1':0, 'Q2':1, 'Q3':2, 'Q4':3}

In [24]:
sales_matrix[rdict['US']][qdict['Q3']]

3323

In [25]:
sales_matrix[1][3]

2342

In [26]:
a= np.arange(0,20)

In [27]:
np.reshape(a,(4,5))

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [28]:
np.reshape(a,(4,5),'F')

array([[ 0,  4,  8, 12, 16],
       [ 1,  5,  9, 13, 17],
       [ 2,  6, 10, 14, 18],
       [ 3,  7, 11, 15, 19]])

In [29]:
list1 = [1,2,3,4]
list2 = [5,6,7,8]
a1 = np.array(list1)
a2 = np.array(list2)


In [30]:
a1

array([1, 2, 3, 4])

In [31]:
a2

array([5, 6, 7, 8])

In [32]:
np.add(a1,a2)

array([ 6,  8, 10, 12])

In [33]:
np.subtract(a1,a2)

array([-4, -4, -4, -4])

In [34]:
np.power(a1,3)

array([ 1,  8, 27, 64], dtype=int32)

In [35]:
np.median(a1)

2.5

In [37]:
np.mean(a1)

2.5

In [38]:
np.average(a1)

2.5

In [39]:
np.std(a1)

1.118033988749895

In [40]:
np.var(a1)

1.25

In [41]:
np.cumsum(a1)

array([ 1,  3,  6, 10], dtype=int32)